studio/api/urls.py
from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register(r'subcategory', SubCategoryViewSet,basename='subcategory')
router.register(r'category', CategoryViewSet,basename='category')
router.register(r'generics',GenericViewSet,basename='generics')
router.register(r'profile_setup', AddStudioViewSet, basename='add_studio')
router.register(r'update_studio', UpdateStudioViewSet,basename='update_studio')
router.register(r'edit_studio', EditStudioViewset,basename='edit_studio')
router.register(r'specific_user_category', SpecificStudioViewSet,basename='Specific_Studio_Detail')
router.register(r'nearby_user_category', StudioMapViewset,basename='nearby_user_category_list')
router.register(r'genre_wise_studio', GenreWiseStudioViewSet,basename='category')
router.register(r'reviews', RatingViewSet, basename='Rating')
router.register(r'specific_studio_reviews', SpecificStudioRatingViewSet, basename='Rating')
router.register(r'favourite_studio', FavouriteStudioViewsets, basename='fav_studio')
router.register(r'get_studio', GetSpecificStudioViewSet, basename='GetSpecificStudioViewSet')
router.register(r'raise_dispute', RaiseDisputeViewset, basename='raise_dispute')
router.register(r'check_slots_availability', CheckAvailabilityViewset, basename='check_slots_availability')

urlpatterns = router.urls

studio/urls.py
from django.urls import path, re_path,include
# from django.contrib.auth import views as auth_views
# from .forms import EmailValidationOnForgotPassword
from .views import studio,generic,sub_category,raise_dispute,category, rating,studioblock



urlpatterns = [
    #--------------------Studio-----------------------------------------
    path('studio', studio.list, name='studio'),
    path('studio/getlist', studio.get_list, name='studio_list'),
    path('studio/add', studio.add, name='studio.add'),
    path('studio/updatestatus', studio.update_status,
         name='studio.updateStatus'),
    path('studio/edit/<int:id>', studio.edit, name='studio.edit'),
    path('studio/view/<int:id>', studio.view, name='studio.view'),
    path('studio/delete/<int:id>', studio.delete, name='studio.delete'),
    path('studio/subcategoryoptions', studio.subcategory_options, name='subcategory_options'),

#-----------------------------generic----------------------------------------
    path('generic', generic.list, name='generic'),
    path('generic/getlist', generic.get_list, name='generic_list'),
    path('generic/add', generic.add, name='generic.add'),
    path('generic/updatestatus', generic.update_status,
         name='generic.updateStatus'),
    path('generic/edit/<int:id>', generic.edit, name='generic.edit'),
    path('generic/view/<int:id>', generic.view, name='generic.view'),
    path('generic/delete/<int:id>', generic.delete, name='generic.delete'),

#---------------------------------SubCategory---------------------------------
    path('subcategory', sub_category.list, name='sub_category'),
    path('subcategory/getlist', sub_category.get_list, name='sub_category_list'),
    path('subcategory/add', sub_category.add, name='sub_category.add'),
    path('subcategory/updatestatus', sub_category.update_status,
         name='sub_category.updateStatus'),
    path('subcategory/edit/<int:id>', sub_category.edit,
         name='sub_category.edit'),
    path('subcategory/view/<int:id>', sub_category.view,
         name='sub_category.view'),
    path('subcategory/delete/<int:id>', sub_category.delete,
         name='sub_category.delete'),

    path('raisedispute', raise_dispute.list, name='raise_dispute'),
    path('raisedispute/getlist', raise_dispute.get_list, name='raise_dispute_list'),
    path('raisedispute/updatestatus', raise_dispute.update_status,
         name='raise_dispute.updateStatus'),
    path('raisedispute/edit/<int:id>', raise_dispute.edit,
         name='raise_dispute.edit'),
    path('raisedispute/view/<int:id>', raise_dispute.view,
         name='raise_dispute.view'),

    path('category', category.list, name='category'),
    path('category/getlist', category.get_list, name='category_list'),
    path('category/add', category.add, name='category.add'),
    path('category/updatestatus', category.update_status,
         name='category.updateStatus'),
    path('category/edit/<int:id>', category.edit,
         name='category.edit'),
    path('category/view/<int:id>', category.view,
         name='category.view'),
    path('category/delete/<int:id>', category.delete,
         name='category.delete'),

path('rating', rating.list, name='rating'),
    path('rating/getlist', rating.get_list, name='rating_list'),
    path('rating/add', rating.add, name='rating.add'),
    path('rating/updatestatus', rating.update_status,
         name='rating.updateStatus'),
    path('rating/edit/<int:id>', rating.edit,
         name='rating.edit'),
    path('rating/view/<int:id>', rating.view,
         name='rating.view'),
    path('rating/delete/<int:id>', rating.delete,
         name='rating.delete'),
    path('studioblock', studioblock.list, name='studioblock'),
    path('studioblock/getlist', studioblock.get_list, name='studioblock_list'),
    path('studioblock/view/<int:id>', studioblock.view,
         name='studioblock.view'),
    path('studioblock/updatestatus', studioblock.update_status,
         name='studioblock.updateStatus'),
     path('studioblock/delete/<int:id>', studioblock.delete,
         name='studioblock.delete'),

]

unlimitedstudio/urls.py
"""unlimitedstudio URL Configuration

The `urlpatterns` list routes URLs to view. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import view
    2. Add a URL to urlpatterns:  path('', view.home, name='home')
Class-based view
    1. Add an import:  from other_app.view import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.contrib.auth import views as auth_views

# from app.views import verifyEmail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myadmin/', include('myadmin.urls')),
    path('api/v1/',include('user.api.urls')),
    path('api/v1/studio/',include('studio.api.urls')),
    path('api/v1/booking/',include('booking.api.urls')),
    path('settings/',include('setting.api.urls')),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    # path('accounts', include('django.contrib.auth.urls')),
    # path('api/', include('api.urls')),

    # path('verify_email/<uidb64>/', verifyEmail, name='verify_email'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path ,include

# from .forms import EmailValidationOnForgotPassword
from .views import *
from user.view import notification
from rest_framework.routers import DefaultRouter
router=DefaultRouter()
router.register('get_list',Get_list_api,basename='admin_get_user_list')

urlpatterns = [
    path('user/', list, name='user'),
    path('userlist/', get_list, name='user_list'),
    path('user/add/',add, name='user.add'),
    path('user/updatestatus/', update_status, name='user.updateStatus'),
    path('user/edit/<int:id>/', edit, name='user.edit'),
    path('user/view/<int:id>/', view, name='user.view'),
    path('user/delete/<int:id/', delete, name='user.delete'),
    path('notification/',notification.list, name='notification'),
    path('notificationlist/', notification.get_list, name='notification_list'),
    path('notification/add/',notification.add, name='notification.add'),
    path('notification/updatestatus/', notification.update_status, name='notification.updateStatus'),
    path('notification/view/<int:id>/', notification.view, name='notification.view'),
    path('notification/delete/<int:id>/', notification.delete, name='notification.delete'),
    path('api/',include(router.urls))
]

studio/forms.py
from django import forms
from django.contrib.admin.views import autocomplete
from django.contrib.auth.forms import PasswordResetForm
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory, BaseInlineFormSet

from .models import *

# Create your forms here.
day = (
    ('Mon', 'Monday'),
    ('Tue', 'Tuesday'),
    ('Wed', 'Wednesday'),
    ('Thu', 'Thursday'),
    ('Fri', 'Friday'),
    ('Sat', 'Saturday'),
    ('Sun', 'Sunday'))


class StudioForm(forms.ModelForm):
    # image = forms.FileField(required=False)
    # availibility = forms.MultipleChoiceField(choices=day)
    # start_time = forms.TimeField()
    # end_time = forms.TimeField()

    # image = forms.FileField(required=False)
    studio_name = forms.CharField()
    category = forms.SelectMultiple(attrs={'required': True})
    subcategory = forms.SelectMultiple(attrs={'required': True})
    generic = forms.SelectMultiple(attrs={'required': True})
    # days = forms.MultipleChoiceField(choices=day)
    # start_time = forms.TimeField()
    # end_time = forms.TimeField()
    # ServiceName = forms.CharField(label='Service Name', required=True)
    # ServicePrice = forms.CharField(label='Service Price', required=True)
    # description = forms.CharField(widget=forms.Textarea)

    created_by = forms.ModelChoiceField(queryset=User.objects.filter(role_id=3),
                                  required=True,
                                  label='Studio Owner',
                                  empty_label='Select Service Provider',
                                  widget=forms.Select(attrs={'class': 'form-control', 'required': False}))
    class Meta:
        model = Studio
        fields = ['studio_name','category','subcategory','generic','created_by','price',
                  'instagram','twitter','facebook','description'

                  ]

    def __init__(self, *args, **kwargs):
        super(StudioForm, self).__init__(*args, **kwargs)
        # print(self.fields,'---------------------25')
        self.fields['generic'].widget.attrs['class'] = 'select2multiple'
        self.fields['category'].widget.attrs['class'] = 'select2multiple'
        self.fields['subcategory'].widget.attrs['class'] = 'select2multiple'
        # self.fields['days'].widget.attrs['class'] = 'select2multiple'



class StudioAvailabilityForm(forms.ModelForm):
    days = forms.MultipleChoiceField(choices=day)

    class Meta:
        model = StudioAvailability
        fields = ['days', 'start_time', 'end_time']

    # def __init__(self, *args, **kwargs):
    #     super(StudioAvailabilityForm, self).__init__(*args, **kwargs)
    #     self.fields['days'].widget.attrs['class'] = 'select2multiple'


# StudioFormSet = inlineformset_factory(
#     Studio,
#     StudioAvailability,
#     fields=('days',
#             'start_time',
#             'end_time',
#             ),
#     widgets={
#             'days': forms.MultipleChoiceField(choices=day),
#             'start_time': forms.TimeInput(attrs={
#                 'type': 'time'
#             }),
#             'end_time': forms.TimeInput(attrs={
#                 'type': 'time'
#             })},
#     extra=1,
#     can_order=True
# )

class GenericForm(forms.ModelForm):
    name = forms.CharField()

    class Meta:
        model = Generics
        fields = ['name', 'image']

class SubCategoryForm(forms.ModelForm):
    name = forms.CharField()
    class Meta:
        model = SubCategory
        fields = ['name', 'category']


class RaiseDisputeForm(forms.ModelForm):
    class Meta:
        model = RaiseDispute
        fields = ['comment']


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['service_provider','name','description','image']

studio/views/category.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from ..forms import *
from ..models import *
from unlimitedstudio.settings import DATETIME_FORMAT, UPDATE_SUCCESS_MESSAGE, ADD_SUCCESS_MESSAGE
from unlimitedstudio.utils import *


page_name = "Category"
page_url = "category"




@login_required
def list(request):
    checkRolePermission(request, page_url + "-list")
    show_add = checkRolePermission(request, page_url + "-add", 0)
    cont = {'page_name': page_name, 'page_url': page_url, 'show_add': show_add}
    return render(request, page_url+'/list.html', cont)


@login_required
def get_list(request):
    checkRolePermission(request, page_url + "-list")
    sortable_columns = ['id', 'name','description', 'subcategory', 'price']
    start = int(request.GET.get('start', 1))
    length = int(request.GET.get('length', 1))
    page = (start/length) + 1
    order_dir = request.GET.get('order[0][dir]')
    order_column = int(request.GET.get('order[0][column]'))
    order_by = sortable_columns[order_column]
    keyword = request.GET.get('search[value]')
    if order_dir == "desc":
        order_by = '-{}'.format(order_by)
    print('==================================39')
    data_list = Category.objects.all().filter(Q(name__icontains=keyword)).order_by(order_by)
    print(data_list,'==============================41')
    paginator = Paginator(data_list, length)

    try:
        records = paginator.page(page)
    except PageNotAnInteger:
        records = paginator.page(1)
    except EmptyPage:
        records = paginator.page(paginator.num_pages)
    i = 1
    datas = []
    for record in records:

        actions = '<div class="btn-group" role="group" aria-label="User Actions">'
        if checkRolePermission(request, page_url + "-edit", 0) == True:
            actions += create_edit(record.id, page_url + '.edit')
        if checkRolePermission(request, page_url + "-view", 0) == True:
            actions += create_view(record.id, page_url + '.view')
        # if checkRolePermission(request, page_url + "-delete", 0) == True:
        #     actions += create_delete(record.id, page_url+'.delete')
        actions += '</div>'

        u = {
            'sno': start + i,
            'name': record.name,
            'service_provider':record.service_provider,
            'description':record.description,
            'status': record.status,
            'created_date': record.created_date.strftime(DATETIME_FORMAT),
            'actions': actions
        }
        i = i+1
        datas.append(u)
    data = {
        # 'draw': request.draw,
        'recordsFiltered': paginator.count,
        'recordsTotal': paginator.count,
        'data': datas
    }
    return JsonResponse(data)


@login_required
def add(request):
    checkRolePermission(request, page_url + "-add")
    form = CategoryForm()
    if request.method == 'POST':
        print(request.POST,"POST")
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            print('------------------89')
            form.save()
            # data.status = True
            # data.save()
            messages.add_message(request, messages.SUCCESS, ADD_SUCCESS_MESSAGE)
            return redirect(page_url)
        else:
            pass
    cont = {
        'page_name': page_name,
        'page_url': page_url,
        'forms': form
    }
    return render(request, page_url+'/add.html', cont)


@login_required
def update_status(request):
    checkRolePermission(request, page_url + "-edit")
    if request.method == 'GET':
        id = request.GET.get('id')
        status = request.GET.get('status')
        data = Category.objects.get(pk=id)
        data.status = status
        data.save()
        response = {
            'status': 'success'
        }
    else:
        response = {
            'status': 'failed'
        }
    return JsonResponse(response)


@login_required
def edit(request, id):
    checkRolePermission(request, page_url + "-edit")
    obj = get_object_or_404(Category, id=id)
    form = CategoryForm(instance=obj)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=obj)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, UPDATE_SUCCESS_MESSAGE)
            return redirect(page_url)
    cont = {
        'page_name': page_name,
        'page_url': page_url,
        'forms': form,
        'id': id
    }
    return render(request, page_url+'/edit.html', cont)


@login_required
def view(request, id):
    checkRolePermission(request, page_url + "-view")
    data = Category.objects.get(pk=id)
    cont = {
        'page_name': page_name,
        'page_url': page_url,
        'data': data
    }
    return render(request, page_url+'/view.html', cont)


@login_required
def delete(request, id):
    checkRolePermission(request, page_url + "-delete")
    if request.method == 'GET':
        data = Category.objects.get(pk=id)
        data.delete()
        response = {
            'status': 'success'
        }
    else:
        response = {
            'status': 'failed'
        }
    return JsonResponse(response)

studio/templates/studio/add.html
{% extends 'layouts/admin.html' %}
{% load static %}
{% block 'maincontent' %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{page_name}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item"><a href="{% url page_url %}">{{page_name}}</a></li>
              <li class="breadcrumb-item active">Add {{page_name}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add {{page_name}}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="POST" data-cities-url="{% url 'subcategory_options' %}"
                    action="{% url 'studio.add' %}" novalidate>
                {% include "./form.html" %}
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endblock %}
{% block 'script' %}
<script>
function subcategoryoptions(){
    var url = $("#quickForm").attr("data-cities-url");
      var countryId = $("#id_category").val();
      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_subcategory").html(data);
        }
      });
  }
    $("#id_category").change(function () {
      var url = $("#quickForm").attr("data-cities-url");
      var countryId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_subcategory").html(data);
        }
      });
    });

    window.onload = subcategoryoptions()
</script>

{% endblock %}

studio/templates/studio/edit.html
{% extends 'layouts/admin.html' %}
{% load static %}
{% block 'maincontent' %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{page_name}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item"><a href="{% url page_url %}">{{page_name}}</a></li>
              <li class="breadcrumb-item active">Edit {{page_name}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit {{page_name}}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" method="POST" data-cities-url="{% url 'subcategory_options' %}"
                    action="{% url 'studio.edit' id %}" novalidate >
                {% include "./form.html" %}
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endblock %}
{% block 'script' %}
<script>
  function subcategoryoptions(){
    var url = $("#quickForm").attr("data-cities-url");
      var countryId = $("#id_category").val();
      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_subcategory").html(data);
        }
      });
  }
    $("#id_category").change(function () {
      var url = $("#quickForm").attr("data-cities-url");
      var countryId = $(this).val();
      console.log(countryId,'countryId')
      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_subcategory").html(data);
        }
      });
    });
    window.onload = subcategoryoptions()
</script>

{% endblock %}

studio/templates/studio/form.html
{% csrf_token %}
{% load widget_tweaks %}
<div class="card-body">
    <div class="row">

{% for field in forms %}
      <div class="col-md-12">
        <div class="form-group">
          <label for="{{ field.auto_id }}">{{ field.label }}</label>
            {{ field | add_class:"form-control"}}
            <!--          <input type="text" value="{% if form.it_title.value != None %}{{ form.it_title.value }}{% endif %}" name="it_title" class="form-control" id="it_title" placeholder="Enter italian title">-->
          {% if field.help_text %}
            <small>{{ field.help_text|safe }}</small>
          {% endif %}
            {% for error in field.errors %}
            <small id="{{ field.auto_id }}" class="text-danger">{{ error }}</small>
          {% endfor %}

        </div>
      </div>
{% endfor %}
    </div>
  </div>
  <!-- /.card-body -->
<div class="card-footer">
  <a href="{% url page_url %}" class="btn btn-secondary">Cancel</a>
  <button type="submit" class="btn btn-primary float-right">Submit</button>
</div>

studio/templates/studio/list.html
{% extends 'layouts/admin.html' %}
{% load static %}
{% block 'maincontent' %}
{% load common_tags %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
             <h1>{{page_name}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item active">{{page_name}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
<!--                {% if show_add == True %}-->
<!--               <a href="{% url 'studio.add' %}">-->
<!--                  <button class="btn btn-primary btn-round ml-auto">-->
<!--                    <i class="fas fa-plus"> </i> &nbsp; Add {{page_name}}-->
<!--                  </button>-->
<!--                </a>-->
<!--                {% endif %}-->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>SubCategory</th>
                    <th>Generic</th>
<!--                    <th>Price</th>-->
                    <th>Service Provider</th>
                    <th class="action">Action</th>
                  </tr>
                  </thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>SubCategory</th>
                    <th>Generic</th>
<!--                    <th>Price</th>-->
                    <th>Service Provider</th>
                    <th>Action</th>
                  </tr>
                  <tfoot>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endblock %}
{% block 'script' %}
<script>
  $(function () {
    Gurl="{% url 'admin_get_user_list-list' %}?format=datatables"
   tables = $('#example1').DataTable({
        "bProcessing": true,
        "serverSide": true,
        "pageLength": 10,
        "order": [[0, "desc"]],

        "ajax": {
            url: "{% url 'studio_list' %}",
            //method:"POST",
            error: function () {
                alert("something went wrong");
            }
        },

        "aoColumns": [
            {mData: 'sno'},
            {mData: 'name'},
            {mData: 'category'},
            {mData: 'sub_category'},
            {mData: 'generic'},
<!--            {mData: 'price'},-->
            {mData: 'user'},
            {mData: 'actions'}
        ],
        language: {
                searchPlaceholder: "Search"
        },
        "aoColumnDefs": [
            {"bSortable": false, "aTargets": ['action']},

        ],
        "fnDrawCallback": function() {

        },
    });

    tables.state.clear()
  });

</script>
{% endblock %}

studio/templates/studio/subcategory_dropdown_list_options.html
{% for subcategories in subcategory %}
<option value="{{ subcategories.pk }}">{{ subcategories.name }}</option>
{% endfor %}

studio/templates/studio/view.html
{% extends 'layouts/admin.html' %}
{% load static %}
{% block 'maincontent' %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{page_name}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
              <li class="breadcrumb-item"><a href="{% url page_url %}">{{page_name}}</a></li>
              <li class="breadcrumb-item active">View {{page_name}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-striped table-bordered">
                 <tbody>
                  <tr>
                    <th width="30%">Name</th>
                    <td>{{data.name}}</td>
                  </tr>
                 <tr>
                    <th>Description</th>
                    <td>{{data.description}}</td>
                  </tr>
                 <tr>
                    <th>SubCategory</th>
                    <td>{{data.subcategory.name}}</td>
                  </tr>
                 <tr>
                    <th>Generic</th>
                   <td>
                   {% for generic in data.generic.all %}
                    {{generic.name}},
                     {% endfor %}
                   </td>
                  </tr>
                 <tr>
                    <th>instagram</th>
                   <td>
                    {{data.instagram}}
                   </td>
                  </tr>
                 <tr>
                    <th>twitter</th>
                   <td>
                    {{data.twitter}}
                   </td>
                  </tr>
                 <tr>
                    <th>facebook</th>
                   <td>
                    {{data.facebook}}
                   </td>
                  </tr>
                 <tr>
                    <th>Owner</th>
                   <td>
                    {{data.created_by.first_name}} {{data.created_by.first_name}}
                   </td>
                 </tr>
                 <tr>
                    <th>facebook</th>
                   <td>
                    {{data.facebook}}
                   </td>
                  </tr>

                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
                <div class="card-footer">
                  <a href="{% url page_url %}" class="btn btn-secondary">Cancel</a>
                </div>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endblock %}